recipes-kernel/perf/perf.bbappend: Fixes for 6.9 kernel
This works around a few problems seen building with the new 6.9 kernel.
Two of these are effectively backports from upstream poky:

- perf: fix build with latest kernel
  https://git.yoctoproject.org/poky/commit/?id=683aff7a081bb20a36506d93eb98e993c94e3c15

- perf: add asm include required for v6.9+
  https://git.yoctoproject.org/poky/commit/?id=8650a98b270b769f869fe796828083ff00463bb1

both require adding extra directories to be copied over from the kernel
source directory.

A third issue which has been seen is a failure when trying to build
bpftool:

| make[3]: *** ../bpf/bpftool: No such file or directory.  Stop.

Initial attempts to fix this by copying over tools/bpf/bpftool fix the
immediate problem but then failed with the error:

In file included from bpf.c:37:
libbpf_internal.h:18:10: fatal error: libelf.h: No such file or directory
   18 | #include <libelf.h>
      |          ^~~~~~~~~~

It appears as if this directory is built without using $BUILD_CFLAGS
so the sysroot isn't set correctly.

Rather than try and fix this, fix the issue which is now causing the
build to need $(BPFTOOL) while it didn't previously. With the old
kernel when BUILD_BPF_SKEL wasn't set, this had the behaviour of not
building anything which depended on BPF skeleton support. In newer
kernels the default behaviour has changed, when BUILD_BPF_SKEL isn't
set the default is to enable features requiring BPF skeleton support.
So explicitly set BUILD_BPF_SKEL=0.